name: apiverve_compliments
description: Compliment Generator creates unique, heartfelt compliments using template-based generation with extensive word banks. Perfect for apps, chatbots, or spreading positivity.
version: 1.1.14
homepage: https://apiverve.com/marketplace/compliments?utm_source=dart&utm_medium=homepage
repository: https://github.com/apiverve/compliments-api/tree/main/dart

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  http: ^1.1.0
  http_parser: ^4.0.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
